quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.jdbc.max-size=3
quarkus.datasource.jdbc.acquisition-timeout=10S
quarkus.datasource.jdbc.max-lifetime=20M
quarkus.datasource.jdbc.idle-removal-interval=2M
quarkus.datasource.jdbc.background-validation-interval=2M
quarkus.datasource.jdbc.validation-query-sql=SELECT 1
quarkus.datasource.jdbc.leak-detection-interval=60S
quarkus.datasource.db-version=13.0.0

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,https://nameri-detska.com,https://www.nameri-detska.com,https://frontend-954699636815.europe-west1.run.app
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=content-type
quarkus.http.cors.access-control-max-age=24h

quarkus.cache.caffeine.facilities.expire-after-write=1H

quarkus.http.port=${PORT:8080}

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.log.level=INFO

%dev.quarkus.log.level=DEBUG
