###################################
# Package
###################################
quarkus.package.jar.type=uber-jar

###################################
# Database Properties (PostgreSQL)
###################################
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.jdbc.max-size=3
quarkus.datasource.jdbc.acquisition-timeout=10S
quarkus.datasource.jdbc.max-lifetime=20M
quarkus.datasource.jdbc.idle-removal-interval=2M
quarkus.datasource.jdbc.background-validation-interval=2M
quarkus.datasource.jdbc.validation-query-sql=SELECT 1
quarkus.datasource.jdbc.leak-detection-interval=60S
quarkus.datasource.db-version=13.0.0

###################################
# Kid facilities resources
###################################
municipal.kid.facilities.api.url=https://kg.sofia.bg/api/public/kg/type/kinderGarden/all?filterType=by_region&kgType=0&regionId=0
private.nurseries.srzi.pdf.url=https://kg.sofia.bg/api/public/file/91f643b4bd6a4b179aaec3de09d028af
private.mon.kindergartens.register.url=https://ri-api.mon.bg/data/get/public-register
private.mon.kindergartens.detail.url=https://ri-api.mon.bg/data/get/institution

###################################
# Google Maps Geocoding by Address in Sofia, Bulgaria
###################################
google.maps.geocoding.url-template=https://maps.googleapis.com/maps/api/geocode/json?address={address}&components=country:BG&bounds=42.41237,23.05108%7C42.89656,23.67867&key=${GOOGLE_MAPS_API_KEY}

###################################
# Gemini AI
###################################
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3.1-flash-lite
quarkus.langchain4j.ai.gemini.chat-model.temperature=0.0
